export enum ContextEnum {
  BUSINESS_CREATE = 'BUSINESS_CREATE',
  BUSINESS_UPDATE = 'BUSINESS_UPDATE',

  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
}